/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TalentRouteImport } from './routes/talent'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ForWorkersRouteImport } from './routes/for-workers'
import { Route as ForBusinessesRouteImport } from './routes/for-businesses'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleIndexRouteImport } from './routes/console.index'
import { Route as ConsoleWorkersRouteImport } from './routes/console.workers'
import { Route as ConsoleShiftsRouteImport } from './routes/console.shifts'
import { Route as ConsoleSettingsRouteImport } from './routes/console.settings'
import { Route as ConsoleMatchesRouteImport } from './routes/console.matches'
import { Route as ConsoleEmailsRouteImport } from './routes/console.emails'
import { Route as ConsoleDocumentsRouteImport } from './routes/console.documents'
import { Route as ConsoleDisputesRouteImport } from './routes/console.disputes'
import { Route as ConsoleContentRouteImport } from './routes/console.content'
import { Route as ConsoleBusinessesRouteImport } from './routes/console.businesses'
import { Route as ConsoleAccessRouteImport } from './routes/console.access'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPostJobRouteImport } from './routes/_authenticated/post-job'
import { Route as AuthenticatedMyJobsRouteImport } from './routes/_authenticated/my-jobs'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as ConsoleWorkersWorkerIdRouteImport } from './routes/console.workers.$workerId'
import { Route as ConsoleBusinessesBusinessIdRouteImport } from './routes/console.businesses.$businessId'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentRoute = TalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForWorkersRoute = ForWorkersRouteImport.update({
  id: '/for-workers',
  path: '/for-workers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBusinessesRoute = ForBusinessesRouteImport.update({
  id: '/for-businesses',
  path: '/for-businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleWorkersRoute = ConsoleWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleShiftsRoute = ConsoleShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleMatchesRoute = ConsoleMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleEmailsRoute = ConsoleEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDocumentsRoute = ConsoleDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDisputesRoute = ConsoleDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleContentRoute = ConsoleContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleBusinessesRoute = ConsoleBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAccessRoute = ConsoleAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => ConsoleRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostJobRoute = AuthenticatedPostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyJobsRoute = AuthenticatedMyJobsRouteImport.update({
  id: '/my-jobs',
  path: '/my-jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ConsoleWorkersWorkerIdRoute = ConsoleWorkersWorkerIdRouteImport.update({
  id: '/$workerId',
  path: '/$workerId',
  getParentRoute: () => ConsoleWorkersRoute,
} as any)
const ConsoleBusinessesBusinessIdRoute =
  ConsoleBusinessesBusinessIdRouteImport.update({
    id: '/$businessId',
    path: '/$businessId',
    getParentRoute: () => ConsoleBusinessesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRouteWithChildren
  '/for-businesses': typeof ForBusinessesRoute
  '/for-workers': typeof ForWorkersRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talent': typeof TalentRoute
  '/trust': typeof TrustRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-jobs': typeof AuthenticatedMyJobsRoute
  '/post-job': typeof AuthenticatedPostJobRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/console/access': typeof ConsoleAccessRoute
  '/console/businesses': typeof ConsoleBusinessesRouteWithChildren
  '/console/content': typeof ConsoleContentRoute
  '/console/disputes': typeof ConsoleDisputesRoute
  '/console/documents': typeof ConsoleDocumentsRoute
  '/console/emails': typeof ConsoleEmailsRoute
  '/console/matches': typeof ConsoleMatchesRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/shifts': typeof ConsoleShiftsRoute
  '/console/workers': typeof ConsoleWorkersRouteWithChildren
  '/console/': typeof ConsoleIndexRoute
  '/console/businesses/$businessId': typeof ConsoleBusinessesBusinessIdRoute
  '/console/workers/$workerId': typeof ConsoleWorkersWorkerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/for-businesses': typeof ForBusinessesRoute
  '/for-workers': typeof ForWorkersRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talent': typeof TalentRoute
  '/trust': typeof TrustRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-jobs': typeof AuthenticatedMyJobsRoute
  '/post-job': typeof AuthenticatedPostJobRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/console/access': typeof ConsoleAccessRoute
  '/console/businesses': typeof ConsoleBusinessesRouteWithChildren
  '/console/content': typeof ConsoleContentRoute
  '/console/disputes': typeof ConsoleDisputesRoute
  '/console/documents': typeof ConsoleDocumentsRoute
  '/console/emails': typeof ConsoleEmailsRoute
  '/console/matches': typeof ConsoleMatchesRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/shifts': typeof ConsoleShiftsRoute
  '/console/workers': typeof ConsoleWorkersRouteWithChildren
  '/console': typeof ConsoleIndexRoute
  '/console/businesses/$businessId': typeof ConsoleBusinessesBusinessIdRoute
  '/console/workers/$workerId': typeof ConsoleWorkersWorkerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRouteWithChildren
  '/for-businesses': typeof ForBusinessesRoute
  '/for-workers': typeof ForWorkersRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talent': typeof TalentRoute
  '/trust': typeof TrustRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/my-jobs': typeof AuthenticatedMyJobsRoute
  '/_authenticated/post-job': typeof AuthenticatedPostJobRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/console/access': typeof ConsoleAccessRoute
  '/console/businesses': typeof ConsoleBusinessesRouteWithChildren
  '/console/content': typeof ConsoleContentRoute
  '/console/disputes': typeof ConsoleDisputesRoute
  '/console/documents': typeof ConsoleDocumentsRoute
  '/console/emails': typeof ConsoleEmailsRoute
  '/console/matches': typeof ConsoleMatchesRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/shifts': typeof ConsoleShiftsRoute
  '/console/workers': typeof ConsoleWorkersRouteWithChildren
  '/console/': typeof ConsoleIndexRoute
  '/console/businesses/$businessId': typeof ConsoleBusinessesBusinessIdRoute
  '/console/workers/$workerId': typeof ConsoleWorkersWorkerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/console'
    | '/for-businesses'
    | '/for-workers'
    | '/jobs'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/sitemap.xml'
    | '/talent'
    | '/trust'
    | '/applications'
    | '/dashboard'
    | '/messages'
    | '/my-jobs'
    | '/post-job'
    | '/profile'
    | '/console/access'
    | '/console/businesses'
    | '/console/content'
    | '/console/disputes'
    | '/console/documents'
    | '/console/emails'
    | '/console/matches'
    | '/console/settings'
    | '/console/shifts'
    | '/console/workers'
    | '/console/'
    | '/console/businesses/$businessId'
    | '/console/workers/$workerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/for-businesses'
    | '/for-workers'
    | '/jobs'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/sitemap.xml'
    | '/talent'
    | '/trust'
    | '/applications'
    | '/dashboard'
    | '/messages'
    | '/my-jobs'
    | '/post-job'
    | '/profile'
    | '/console/access'
    | '/console/businesses'
    | '/console/content'
    | '/console/disputes'
    | '/console/documents'
    | '/console/emails'
    | '/console/matches'
    | '/console/settings'
    | '/console/shifts'
    | '/console/workers'
    | '/console'
    | '/console/businesses/$businessId'
    | '/console/workers/$workerId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/console'
    | '/for-businesses'
    | '/for-workers'
    | '/jobs'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/sitemap.xml'
    | '/talent'
    | '/trust'
    | '/_authenticated/applications'
    | '/_authenticated/dashboard'
    | '/_authenticated/messages'
    | '/_authenticated/my-jobs'
    | '/_authenticated/post-job'
    | '/_authenticated/profile'
    | '/console/access'
    | '/console/businesses'
    | '/console/content'
    | '/console/disputes'
    | '/console/documents'
    | '/console/emails'
    | '/console/matches'
    | '/console/settings'
    | '/console/shifts'
    | '/console/workers'
    | '/console/'
    | '/console/businesses/$businessId'
    | '/console/workers/$workerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  ForBusinessesRoute: typeof ForBusinessesRoute
  ForWorkersRoute: typeof ForWorkersRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TalentRoute: typeof TalentRoute
  TrustRoute: typeof TrustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-workers': {
      id: '/for-workers'
      path: '/for-workers'
      fullPath: '/for-workers'
      preLoaderRoute: typeof ForWorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-businesses': {
      id: '/for-businesses'
      path: '/for-businesses'
      fullPath: '/for-businesses'
      preLoaderRoute: typeof ForBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/workers': {
      id: '/console/workers'
      path: '/workers'
      fullPath: '/console/workers'
      preLoaderRoute: typeof ConsoleWorkersRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/shifts': {
      id: '/console/shifts'
      path: '/shifts'
      fullPath: '/console/shifts'
      preLoaderRoute: typeof ConsoleShiftsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/settings': {
      id: '/console/settings'
      path: '/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/matches': {
      id: '/console/matches'
      path: '/matches'
      fullPath: '/console/matches'
      preLoaderRoute: typeof ConsoleMatchesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/emails': {
      id: '/console/emails'
      path: '/emails'
      fullPath: '/console/emails'
      preLoaderRoute: typeof ConsoleEmailsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/documents': {
      id: '/console/documents'
      path: '/documents'
      fullPath: '/console/documents'
      preLoaderRoute: typeof ConsoleDocumentsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/disputes': {
      id: '/console/disputes'
      path: '/disputes'
      fullPath: '/console/disputes'
      preLoaderRoute: typeof ConsoleDisputesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/content': {
      id: '/console/content'
      path: '/content'
      fullPath: '/console/content'
      preLoaderRoute: typeof ConsoleContentRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/businesses': {
      id: '/console/businesses'
      path: '/businesses'
      fullPath: '/console/businesses'
      preLoaderRoute: typeof ConsoleBusinessesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/access': {
      id: '/console/access'
      path: '/access'
      fullPath: '/console/access'
      preLoaderRoute: typeof ConsoleAccessRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post-job': {
      id: '/_authenticated/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof AuthenticatedPostJobRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-jobs': {
      id: '/_authenticated/my-jobs'
      path: '/my-jobs'
      fullPath: '/my-jobs'
      preLoaderRoute: typeof AuthenticatedMyJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/console/workers/$workerId': {
      id: '/console/workers/$workerId'
      path: '/$workerId'
      fullPath: '/console/workers/$workerId'
      preLoaderRoute: typeof ConsoleWorkersWorkerIdRouteImport
      parentRoute: typeof ConsoleWorkersRoute
    }
    '/console/businesses/$businessId': {
      id: '/console/businesses/$businessId'
      path: '/$businessId'
      fullPath: '/console/businesses/$businessId'
      preLoaderRoute: typeof ConsoleBusinessesBusinessIdRouteImport
      parentRoute: typeof ConsoleBusinessesRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMyJobsRoute: typeof AuthenticatedMyJobsRoute
  AuthenticatedPostJobRoute: typeof AuthenticatedPostJobRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMyJobsRoute: AuthenticatedMyJobsRoute,
  AuthenticatedPostJobRoute: AuthenticatedPostJobRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ConsoleBusinessesRouteChildren {
  ConsoleBusinessesBusinessIdRoute: typeof ConsoleBusinessesBusinessIdRoute
}

const ConsoleBusinessesRouteChildren: ConsoleBusinessesRouteChildren = {
  ConsoleBusinessesBusinessIdRoute: ConsoleBusinessesBusinessIdRoute,
}

const ConsoleBusinessesRouteWithChildren =
  ConsoleBusinessesRoute._addFileChildren(ConsoleBusinessesRouteChildren)

interface ConsoleWorkersRouteChildren {
  ConsoleWorkersWorkerIdRoute: typeof ConsoleWorkersWorkerIdRoute
}

const ConsoleWorkersRouteChildren: ConsoleWorkersRouteChildren = {
  ConsoleWorkersWorkerIdRoute: ConsoleWorkersWorkerIdRoute,
}

const ConsoleWorkersRouteWithChildren = ConsoleWorkersRoute._addFileChildren(
  ConsoleWorkersRouteChildren,
)

interface ConsoleRouteChildren {
  ConsoleAccessRoute: typeof ConsoleAccessRoute
  ConsoleBusinessesRoute: typeof ConsoleBusinessesRouteWithChildren
  ConsoleContentRoute: typeof ConsoleContentRoute
  ConsoleDisputesRoute: typeof ConsoleDisputesRoute
  ConsoleDocumentsRoute: typeof ConsoleDocumentsRoute
  ConsoleEmailsRoute: typeof ConsoleEmailsRoute
  ConsoleMatchesRoute: typeof ConsoleMatchesRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleShiftsRoute: typeof ConsoleShiftsRoute
  ConsoleWorkersRoute: typeof ConsoleWorkersRouteWithChildren
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleAccessRoute: ConsoleAccessRoute,
  ConsoleBusinessesRoute: ConsoleBusinessesRouteWithChildren,
  ConsoleContentRoute: ConsoleContentRoute,
  ConsoleDisputesRoute: ConsoleDisputesRoute,
  ConsoleDocumentsRoute: ConsoleDocumentsRoute,
  ConsoleEmailsRoute: ConsoleEmailsRoute,
  ConsoleMatchesRoute: ConsoleMatchesRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleShiftsRoute: ConsoleShiftsRoute,
  ConsoleWorkersRoute: ConsoleWorkersRouteWithChildren,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  ForBusinessesRoute: ForBusinessesRoute,
  ForWorkersRoute: ForWorkersRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TalentRoute: TalentRoute,
  TrustRoute: TrustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
